[project]
name = "alecz-discord-bot"
version = "0.1.0"
description = "An Annoying Bot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord-py[speed]==2.3.2",
    "python-dotenv>=1.2.1",
]
